image: ruby:2.6.8

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  GEM_PATH: .bundle
  BUNDLER_PATH: .bundle/bin

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .bundle
    - .npm

before_script:
  - apt-get update && apt-get install -y build-essential bash git rsync curl gnupg2
  - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
  - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null
  - echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt-get update -y
  - apt-get install -y rbenv nodejs yarn rbenv ruby-build
  - git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
  - rbenv install 2.7.5
  - source /root/.bashrc
  - chmod +x setup.sh && bash setup.sh

test:
  stage: test
  script:
  - $BUNDLER_PATH/bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  stage: deploy
  script:
  - $BUNDLER_PATH/bundle exec jekyll build -d public
  - find public -type f -regex '.*\.\(html\)$' -exec npm run minify-html {} \;
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
  only:
  - main
